In [26]:
import pandas as pd
import numpy as np
import sklearn.metrics
import warnings
warnings.filterwarnings('ignore')

In [27]:
# This line loads the data into a dataframe
mentalhealth_df = pd.read_csv("trainms.csv")

In [28]:
male = set(["male", "m", "male-ish", "maile", "mal", "male (cis)", "make", "male ", "man", "msle", "mail", "malr", "cis man"])
female = set(["cis female", "f", "female", "woman",  "femake", "female ","cis-female/femme", "female (cis)", "femail"])
for i, row in mentalhealth_df.iterrows():
    if row['Gender'].lower() in male:
        mentalhealth_df.set_value(i, 'Gender', "Male")
    elif row['Gender'].lower() in female:
        mentalhealth_df.set_value(i, 'Gender', "Female")
    else:
        mentalhealth_df.set_value(i, 'Gender', "Transgender")
mentalhealth_df.head()

,Timestamp,Age,Gender,Country,state,self_employed,family_history,treatment,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,2014-08-27 11:29:31,37,Female,United States,IL,NaN,No,Yes,Often,6-25,...,Somewhat easy,No,No,Some of them,Yes,No,Maybe,Yes,No,NaN
1,2014-08-27 11:29:37,44,Male,United States,IN,NaN,No,No,Rarely,More than 1000,...,Don't know,Maybe,No,No,No,No,No,Don't know,No,NaN
2,2014-08-27 11:29:44,32,Male,Canada,NaN,NaN,No,No,Rarely,6-25,...,Somewhat difficult,No,No,Yes,Yes,Yes,Yes,No,No,NaN
3,2014-08-27 11:29:46,31,Male,United Kingdom,NaN,NaN,Yes,Yes,Often,26-100,...,Somewhat difficult,Yes,Yes,Some of them,No,Maybe,Maybe,No,Yes,NaN
4,2014-08-27 11:30:22,31,Male,United States,TX,NaN,No,No,Never,100-500,...,Don't know,No,No,Some of them,Yes,Yes,Yes,Don't know,No,NaN

In [29]:
numbersdf = pd.DataFrame()

def yn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)

def ydkn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 2)
    elif row[x] == "Don't know":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)
        
def ymn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 2)
    elif row[x] == "Maybe":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)

def ysotn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 2)
    elif row[x] == "Some of them":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)
        
for i, row in mentalhealth_df.iterrows():
    numbersdf.set_value(i, 'Age', row['Age'])
    if row['Gender'] == "Male":
        numbersdf.set_value(i, 'Gender', 2)
    elif row['Gender'] == "Trans":
        numbersdf.set_value(i, 'Gender', 1)
    else:
        numbersdf.set_value(i, 'Gender', 0)
    yn(i, row, 'family_history')
    yn(i, row, 'treatment')
    if row['work_interfere'] == "Often":
        numbersdf.set_value(i, 'work_interfere', 3)
    elif row['work_interfere'] == "Sometimes":
        numbersdf.set_value(i, 'work_interfere', 2)
    elif row['work_interfere'] == "Rarely":
        numbersdf.set_value(i, 'work_interfere', 1)
    else:
        numbersdf.set_value(i, 'work_interfere', 0)
    if row['no_employees'] == "1-5":
        numbersdf.set_value(i, 'no_employees', 1)
    elif row['no_employees'] == "6-25":
        numbersdf.set_value(i, 'no_employees', 2)
    elif row['no_employees'] == "26-100":
        numbersdf.set_value(i, 'no_employees', 3)
    elif row['no_employees'] == "100-500":
        numbersdf.set_value(i, 'no_employees', 4)
    elif row['no_employees'] == "500-1000":
        numbersdf.set_value(i, 'no_employees', 5)
    elif row['no_employees'] == "More than 1000":
        numbersdf.set_value(i, 'no_employees', 6)
    else:
        numbersdf.set_value(i, 'no_employees', 0)
    yn(i, row, 'remote_work')
    yn(i, row, 'tech_company')
    ydkn(i, row, 'benefits')
    if row['care_options'] == "Yes":
        numbersdf.set_value(i, 'care_options', 2)
    elif row['care_options'] == "Not sure":
        numbersdf.set_value(i, 'care_options', 1)
    else:
        numbersdf.set_value(i, 'care_options', 0)
    ydkn(i, row, 'wellness_program')
    ydkn(i, row, 'seek_help')
    ydkn(i, row, 'anonymity')
    if row['leave'] == "Very Easy":
        numbersdf.set_value(i, 'leave', 4)
    elif row['leave'] == "Somewhat easy":
        numbersdf.set_value(i, 'leave', 3)
    elif row['leave'] == "Somewhat difficult":
        numbersdf.set_value(i, 'leave', 2)
    elif row['leave'] == "Very difficult":
        numbersdf.set_value(i, 'leave', 1)
    else:
        numbersdf.set_value(i, 'leave', 0)
    ymn(i, row, 'mental_health_consequence')
    ymn(i, row, 'phys_health_consequence')
    ysotn(i, row, 'coworkers')
    ysotn(i, row, 'supervisor')
    ymn(i, row, 'mental_health_interview')
    ymn(i, row, 'phys_health_interview')
    ydkn(i, row, 'mental_vs_physical')
    yn(i, row, 'obs_consequence')
numbersdf.head()

,Age,Gender,family_history,treatment,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,37.0,0.0,0.0,1.0,3.0,2.0,0.0,1.0,2.0,1.0,...,2.0,3.0,0.0,0.0,1.0,2.0,0.0,1.0,2.0,0.0
1,44.0,2.0,0.0,0.0,1.0,6.0,0.0,0.0,1.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,32.0,2.0,0.0,0.0,1.0,2.0,0.0,1.0,0.0,0.0,...,1.0,2.0,0.0,0.0,2.0,2.0,2.0,2.0,0.0,0.0
3,31.0,2.0,1.0,1.0,3.0,3.0,0.0,1.0,0.0,2.0,...,0.0,2.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0
4,31.0,2.0,0.0,0.0,0.0,4.0,1.0,1.0,2.0,0.0,...,1.0,0.0,0.0,0.0,1.0,2.0,2.0,2.0,1.0,0.0

In [34]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

models = dict()
models["Random Forest:"] = RandomForestClassifier(n_estimators=10)

X = numbersdf.drop(['treatment'], axis=1)
y = numbersdf['treatment']
X_train, X_test, Y_train, Y_test = train_test_split(X, y, test_size=0.5, random_state=10)
#X_train, Y_train = X,y
# to tain on as much data as possible

ml_df = pd.DataFrame(columns=["Model", "Accuracy"])

def score(model):
    clf = model
    clf.fit(X_train, Y_train)
    prediction = pd.DataFrame(clf.predict(X_test), columns=['predictions'])
    return accuracy_score(Y_test, clf.predict(X_test))
    


i = 0
for name, model in models.items():
    accuracy = score(model)
    ml_df.set_value(i, "Model", name)
    ml_df.set_value(i, "Accuracy", accuracy*100)
    i += 1
    
ml_df

            Model Accuracy
0  Random Forest:  99.2063

In [ ]:
# save the model to disk
import pickle
filename = 'finalized_model.sav'
pickle.dump(model, open(filename, 'wb'))
 
# some time later...
 
# load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.score(X_test, Y_test)
print(result)

In [ ]:
zzzz