In [12]:
import pandas as pd
import numpy as np
import sklearn.metrics
import warnings
warnings.filterwarnings('ignore')

In [13]:
# This line loads the data into a dataframe
mentalhealth_df = pd.read_csv("testms.csv")
mentalhealth_df.head()

,s.no,Timestamp,Age,Gender,Country,state,self_employed,family_history,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,1,2014-08-29 09:29:37,25,Male,United States,PA,No,Yes,Often,6-25,...,Somewhat easy,No,No,Yes,Yes,Maybe,Maybe,Don't know,No,NaN
1,2,2014-08-29 09:31:37,42,male,United States,IN,No,Yes,Sometimes,6-25,...,Don't know,Maybe,No,Some of them,Yes,No,Maybe,Don't know,No,NaN
2,3,2014-08-29 09:31:49,34,male,United States,PA,No,Yes,Often,100-500,...,Very easy,No,No,Yes,Yes,Maybe,Maybe,Don't know,No,NaN
3,4,2014-08-29 09:33:43,26,female,United States,OH,No,No,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,Maybe,Maybe,Don't know,Yes,NaN
4,5,2014-08-29 09:35:46,35,Male,United Kingdom,NaN,No,Yes,Sometimes,1-5,...,Very easy,Yes,Yes,Some of them,Some of them,No,Maybe,Yes,Yes,NaN

In [14]:
male = set(["male", "m", "male-ish", "maile", "mal", "male (cis)", "make", "male ", "man", "msle", "mail", "malr", "cis man"])
female = set(["cis female", "f", "female", "woman",  "femake", "female ","cis-female/femme", "female (cis)", "femail"])
for i, row in mentalhealth_df.iterrows():
    if row['Gender'].lower() in male:
        mentalhealth_df.set_value(i, 'Gender', "Male")
    elif row['Gender'].lower() in female:
        mentalhealth_df.set_value(i, 'Gender', "Female")
    else:
        mentalhealth_df.set_value(i, 'Gender', "Transgender")
mentalhealth_df.head()

,s.no,Timestamp,Age,Gender,Country,state,self_employed,family_history,work_interfere,no_employees,...,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence,comments
0,1,2014-08-29 09:29:37,25,Male,United States,PA,No,Yes,Often,6-25,...,Somewhat easy,No,No,Yes,Yes,Maybe,Maybe,Don't know,No,NaN
1,2,2014-08-29 09:31:37,42,Male,United States,IN,No,Yes,Sometimes,6-25,...,Don't know,Maybe,No,Some of them,Yes,No,Maybe,Don't know,No,NaN
2,3,2014-08-29 09:31:49,34,Male,United States,PA,No,Yes,Often,100-500,...,Very easy,No,No,Yes,Yes,Maybe,Maybe,Don't know,No,NaN
3,4,2014-08-29 09:33:43,26,Female,United States,OH,No,No,Sometimes,26-100,...,Don't know,Maybe,No,Some of them,No,Maybe,Maybe,Don't know,Yes,NaN
4,5,2014-08-29 09:35:46,35,Male,United Kingdom,NaN,No,Yes,Sometimes,1-5,...,Very easy,Yes,Yes,Some of them,Some of them,No,Maybe,Yes,Yes,NaN

In [15]:
numbersdf = pd.DataFrame()

def yn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)

def ydkn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 2)
    elif row[x] == "Don't know":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)
        
def ymn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 2)
    elif row[x] == "Maybe":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)

def ysotn(i, row, x):
    if row[x] == "Yes":
        numbersdf.set_value(i, x, 2)
    elif row[x] == "Some of them":
        numbersdf.set_value(i, x, 1)
    else:
        numbersdf.set_value(i, x, 0)
        
for i, row in mentalhealth_df.iterrows():
    numbersdf.set_value(i, 'Age', row['Age'])
    if row['Gender'] == "Male":
        numbersdf.set_value(i, 'Gender', 2)
    elif row['Gender'] == "Trans":
        numbersdf.set_value(i, 'Gender', 1)
    else:
        numbersdf.set_value(i, 'Gender', 0)
    yn(i, row, 'family_history')
    if row['work_interfere'] == "Often":
        numbersdf.set_value(i, 'work_interfere', 3)
    elif row['work_interfere'] == "Sometimes":
        numbersdf.set_value(i, 'work_interfere', 2)
    elif row['work_interfere'] == "Rarely":
        numbersdf.set_value(i, 'work_interfere', 1)
    else:
        numbersdf.set_value(i, 'work_interfere', 0)
    if row['no_employees'] == "1-5":
        numbersdf.set_value(i, 'no_employees', 1)
    elif row['no_employees'] == "6-25":
        numbersdf.set_value(i, 'no_employees', 2)
    elif row['no_employees'] == "26-100":
        numbersdf.set_value(i, 'no_employees', 3)
    elif row['no_employees'] == "100-500":
        numbersdf.set_value(i, 'no_employees', 4)
    elif row['no_employees'] == "500-1000":
        numbersdf.set_value(i, 'no_employees', 5)
    elif row['no_employees'] == "More than 1000":
        numbersdf.set_value(i, 'no_employees', 6)
    else:
        numbersdf.set_value(i, 'no_employees', 0)
    yn(i, row, 'remote_work')
    yn(i, row, 'tech_company')
    ydkn(i, row, 'benefits')
    if row['care_options'] == "Yes":
        numbersdf.set_value(i, 'care_options', 2)
    elif row['care_options'] == "Not sure":
        numbersdf.set_value(i, 'care_options', 1)
    else:
        numbersdf.set_value(i, 'care_options', 0)
    ydkn(i, row, 'wellness_program')
    ydkn(i, row, 'seek_help')
    ydkn(i, row, 'anonymity')
    if row['leave'] == "Very Easy":
        numbersdf.set_value(i, 'leave', 4)
    elif row['leave'] == "Somewhat easy":
        numbersdf.set_value(i, 'leave', 3)
    elif row['leave'] == "Somewhat difficult":
        numbersdf.set_value(i, 'leave', 2)
    elif row['leave'] == "Very difficult":
        numbersdf.set_value(i, 'leave', 1)
    else:
        numbersdf.set_value(i, 'leave', 0)
    ymn(i, row, 'mental_health_consequence')
    ymn(i, row, 'phys_health_consequence')
    ysotn(i, row, 'coworkers')
    ysotn(i, row, 'supervisor')
    ymn(i, row, 'mental_health_interview')
    ymn(i, row, 'phys_health_interview')
    ydkn(i, row, 'mental_vs_physical')
    yn(i, row, 'obs_consequence')
numbersdf.head()

,Age,Gender,family_history,work_interfere,no_employees,remote_work,tech_company,benefits,care_options,wellness_program,...,anonymity,leave,mental_health_consequence,phys_health_consequence,coworkers,supervisor,mental_health_interview,phys_health_interview,mental_vs_physical,obs_consequence
0,25.0,2.0,1.0,3.0,2.0,1.0,1.0,2.0,2.0,0.0,...,2.0,3.0,0.0,0.0,2.0,2.0,1.0,1.0,1.0,0.0
1,42.0,2.0,1.0,2.0,2.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,2.0,0.0,1.0,1.0,0.0
2,34.0,2.0,1.0,3.0,4.0,0.0,1.0,2.0,2.0,0.0,...,2.0,0.0,0.0,0.0,2.0,2.0,1.0,1.0,1.0,0.0
3,26.0,0.0,0.0,2.0,3.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,1.0,1.0,1.0
4,35.0,2.0,1.0,2.0,1.0,0.0,1.0,0.0,2.0,0.0,...,2.0,0.0,2.0,2.0,1.0,1.0,0.0,1.0,2.0,1.0

In [16]:
# save the model to disk
import pickle
filename = 'finalized_model.sav'
loaded_model = pickle.load(open(filename, 'rb'))
result = loaded_model.predict(numbersdf)
prediction = pd.DataFrame(np.where(result > 0, 'Yes', 'No'), columns=['treatment'])
prediction.index += 1
prediction.index.name='s.no'
prediction.to_csv('prediction.csv')